"use client";

import { DATA } from "@/data/resume";
import { QUOTE_TRACES } from "@/data/quote-traces";
import { useLive, useReducedMotion } from "@/hooks/use-live";
import { cn } from "@/lib/utils";
import { useEffect, useMemo, useRef, useState } from "react";

const QUOTES = DATA.contact.quotes;
const H = 96;
const MID = H / 2;
const CYCLE = 5000;
const FORM = 1500; // wave bends into the words from both ends towards the middle
const HOLD = 3500; // words start unravelling from the middle out to both sides
const UNFORM = 1200;
const STAGGER = 0.6; // how far the ends of the quote lead the middle
const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

const clamp = (t: number) => Math.min(1, Math.max(0, t));
const ease = (t: number) => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2);

/** The raw signal: a few sines, in pixels, scrolling left over time. */
function signal(x: number, phase: number) {
  const t = ((x + phase) / 1200) * Math.PI * 2;
  return Math.sin(t * 3) * 10 + Math.sin(t * 7 + 1) * 4 + Math.sin(t * 13) * 2;
}

/** Letter outlines generated by scripts/quote-traces.py, in em (y up from the baseline). */
function decode(text: string) {
  const tr = QUOTE_TRACES[text];
  if (!tr) return null;
  const v = (i: number) => ALPHABET.indexOf(tr.pts[i]) * 64 + ALPHABET.indexOf(tr.pts[i + 1]);
  const xs: number[] = [];
  const ys: number[] = [];
  for (let i = 0; i < tr.pts.length; i += 4) {
    xs.push(v(i) / 150);
    ys.push((v(i + 2) - 100) / 150);
  }
  return { xs, ys, breaks: new Set(tr.breaks), adv: tr.adv, cap: tr.cap };
}

/**
 * An oscilloscope trace across the top of Contact. Every five seconds the
 * middle of the signal bends itself into the outline of a short quote, from
 * both ends towards the middle, holds, then unravels from the middle out to
 * both sides; the next quote comes in its
 * project's colour. The amplitude jumps when you point at a contact button.
 * Runs only while on screen; reduced motion shows the first quote, formed.
 */
export function ScopeTrace({ className }: { className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const path = useRef<SVGPathElement>(null);
  const live = useLive(ref, 0.4);
  const reduced = useReducedMotion();
  const [index, setIndex] = useState(0);
  const clock = useRef(0);
  const phase = useRef(0);
  const amp = useRef(1);

  const quote = QUOTES[index];
  const shape = useMemo(() => decode(quote.text), [quote.text]);

  useEffect(() => {
    const box = ref.current;
    const el = path.current;
    if (!box || !el) return;
    const contact = box.closest("#contact");

    const draw = (P: number) => {
      const W = box.clientWidth;
      const a = amp.current;
      let d = "";
      const wave = (x: number) => MID + signal(x, phase.current) * a;
      if (!shape) {
        for (let x = 0; x <= W + 6; x += 6) d += `${d ? "L" : "M"}${x} ${wave(x).toFixed(1)}`;
        el.setAttribute("d", d);
        return;
      }
      const size = Math.min(34, (W - 40) / shape.adv);
      const left = (W - shape.adv * size) / 2;
      const base = MID + (shape.cap * size) / 2;
      const from = left - 24;
      const to = left + shape.adv * size + 24;
      const n = shape.xs.length;
      // 0 at both ends, 1 in the middle: the ends form first and clear last.
      const order = (u: number) => 1 - Math.abs(u - 0.5) * 2;
      const at = (u: number) => ease(clamp(P * (1 + STAGGER) - STAGGER * order(u)));

      for (let x = 0; x < from; x += 6) d += `${d ? "L" : "M"}${x} ${wave(x).toFixed(1)}`;
      for (let i = 0; i < n; i++) {
        const u = i / (n - 1);
        const e = at(u);
        const wx = from + (to - from) * u;
        const x = wx + (left + shape.xs[i] * size - wx) * e;
        const y = wave(wx) + (base - shape.ys[i] * size - wave(wx)) * e;
        // Once formed, lift the pen between letter contours and at the ends.
        const lift = (i === 0 || shape.breaks.has(i)) && e > 0.5;
        d += `${lift || !d ? "M" : "L"}${x.toFixed(1)} ${y.toFixed(1)}`;
      }
      let first = true;
      for (let x = Math.ceil(to / 6) * 6; x <= W + 6; x += 6) {
        d += `${first && at(1) > 0.5 ? "M" : "L"}${x} ${wave(x).toFixed(1)}`;
        first = false;
      }
      el.setAttribute("d", d);
    };

    const progress = (t: number) => (t < HOLD ? clamp(t / FORM) : 1 - clamp((t - HOLD) / UNFORM));

    if (reduced) {
      const redraw = () => draw(1);
      redraw();
      const ro = new ResizeObserver(redraw);
      ro.observe(box);
      return () => ro.disconnect();
    }
    if (!live) {
      draw(progress(clock.current));
      return;
    }

    let raf = 0;
    let last = performance.now();
    const tick = (now: number) => {
      const dt = Math.min(100, now - last);
      last = now;
      phase.current += dt * 0.12;
      const target = contact?.matches(':has(.btn:hover, [data-term-focus="true"])') ? 2.4 : 1;
      amp.current += (target - amp.current) * Math.min(1, dt / 120);
      clock.current += dt;
      if (clock.current >= CYCLE) {
        clock.current = 0;
        setIndex((i) => (i + 1) % QUOTES.length);
      }
      draw(progress(clock.current));
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [live, reduced, shape]);

  return (
    <div
      ref={ref}
      aria-hidden
      data-scope={quote.accent}
      className={cn("pointer-events-none relative overflow-hidden select-none", className)}
      style={{ height: H }}
    >
      <svg className="absolute inset-0 h-full w-full overflow-visible">
        <defs>
          <pattern id="scope-grid" width="40" height="20" patternUnits="userSpaceOnUse">
            <path d="M40 0H0V20" fill="none" stroke="var(--line)" strokeWidth="1" />
          </pattern>
        </defs>
        <rect width="100%" height="100%" fill="url(#scope-grid)" opacity="0.6" />
        <path
          ref={path}
          fill="none"
          stroke="var(--acc)"
          strokeWidth="1.6"
          strokeLinejoin="round"
          strokeLinecap="round"
          style={{ filter: "drop-shadow(0 0 3px color-mix(in srgb, var(--acc) 30%, transparent))" }}
        />
      </svg>
    </div>
  );
}
